-- Fix database issues for smart-summarizer
-- Run this in Supabase SQL Editor

-- =====================================================
-- 1. Fix embedding dimension mismatch (1536 → 384)
-- =====================================================

-- Check current dimension
DO $$
DECLARE
  current_dim INTEGER;
BEGIN
  SELECT atttypmod - 4 INTO current_dim
  FROM pg_attribute
  WHERE attrelid = 'public.notes'::regclass 
    AND attname = 'embedding';
  
  RAISE NOTICE 'Current embedding dimension: %', current_dim;
END $$;

-- Drop and recreate with correct dimension (384 for Xenova/all-MiniLM-L6-v2)
ALTER TABLE public.notes DROP COLUMN IF EXISTS embedding CASCADE;
ALTER TABLE public.notes ADD COLUMN embedding vector(384);

-- Create index for vector similarity search
CREATE INDEX IF NOT EXISTS notes_embedding_idx ON public.notes 
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

COMMENT ON COLUMN public.notes.embedding IS 
'Vector embedding (384-dim) generated by Xenova/all-MiniLM-L6-v2 for semantic search';

-- =====================================================
-- 2. Ensure canvas_versions table exists
-- =====================================================

CREATE TABLE IF NOT EXISTS public.canvas_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  canvas_id UUID NOT NULL REFERENCES public.canvases(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  version_number INTEGER NOT NULL,
  snapshot_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  change_description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  CONSTRAINT canvas_versions_unique_number UNIQUE (canvas_id, version_number)
);

-- Enable RLS
ALTER TABLE public.canvas_versions ENABLE ROW LEVEL SECURITY;

-- RLS policies for canvas_versions
DROP POLICY IF EXISTS "Users can view their own canvas versions" ON public.canvas_versions;
CREATE POLICY "Users can view their own canvas versions"
  ON public.canvas_versions FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create versions for their own canvases" ON public.canvas_versions;
CREATE POLICY "Users can create versions for their own canvases"
  ON public.canvas_versions FOR INSERT
  WITH CHECK (
    auth.uid() = user_id AND
    EXISTS (
      SELECT 1 FROM public.canvases 
      WHERE id = canvas_id AND user_id = auth.uid()
    )
  );

-- Create index for faster version lookups
CREATE INDEX IF NOT EXISTS canvas_versions_canvas_id_idx 
  ON public.canvas_versions(canvas_id, version_number DESC);

COMMENT ON TABLE public.canvas_versions IS 
'Stores version history snapshots for canvas editing with auto-versioning on save';

-- =====================================================
-- 3. Update or create semantic search RPC functions
-- =====================================================

-- Drop ALL existing function signatures explicitly
-- First, check what signatures exist and drop them all
DO $$
DECLARE
  func_record RECORD;
BEGIN
  -- Drop all match_notes variants
  FOR func_record IN 
    SELECT oid::regprocedure::text AS signature
    FROM pg_proc 
    WHERE proname = 'match_notes' AND pronamespace = 'public'::regnamespace
  LOOP
    EXECUTE 'DROP FUNCTION IF EXISTS ' || func_record.signature || ' CASCADE';
    RAISE NOTICE 'Dropped function: %', func_record.signature;
  END LOOP;
  
  -- Drop all match_notes_by_folder variants
  FOR func_record IN 
    SELECT oid::regprocedure::text AS signature
    FROM pg_proc 
    WHERE proname = 'match_notes_by_folder' AND pronamespace = 'public'::regnamespace
  LOOP
    EXECUTE 'DROP FUNCTION IF EXISTS ' || func_record.signature || ' CASCADE';
    RAISE NOTICE 'Dropped function: %', func_record.signature;
  END LOOP;
END $$;

-- Create match_notes function with 384-dim vector
CREATE OR REPLACE FUNCTION public.match_notes(
  query_embedding vector(384),
  match_threshold FLOAT DEFAULT 0.5,
  match_count INT DEFAULT 5,
  filter_user_id UUID DEFAULT NULL
)
RETURNS TABLE (
  id INT,
  summary TEXT,
  original_notes TEXT,
  persona TEXT,
  created_at TIMESTAMPTZ,
  similarity FLOAT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT
    n.id,
    n.summary,
    n.original_notes,
    n.persona,
    n.created_at,
    1 - (n.embedding <=> query_embedding) AS similarity
  FROM notes n
  WHERE 
    n.embedding IS NOT NULL
    AND (filter_user_id IS NULL OR n.user_id = filter_user_id)
    AND (1 - (n.embedding <=> query_embedding)) >= match_threshold
  ORDER BY n.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Create match_notes_by_folder function with 384-dim vector
CREATE OR REPLACE FUNCTION public.match_notes_by_folder(
  query_embedding vector(384),
  match_threshold FLOAT DEFAULT 0.5,
  match_count INT DEFAULT 5,
  filter_user_id UUID DEFAULT NULL,
  filter_folder_id INT DEFAULT NULL
)
RETURNS TABLE (
  id INT,
  summary TEXT,
  original_notes TEXT,
  persona TEXT,
  created_at TIMESTAMPTZ,
  similarity FLOAT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT
    n.id,
    n.summary,
    n.original_notes,
    n.persona,
    n.created_at,
    1 - (n.embedding <=> query_embedding) AS similarity
  FROM notes n
  WHERE 
    n.embedding IS NOT NULL
    AND (filter_user_id IS NULL OR n.user_id = filter_user_id)
    AND (filter_folder_id IS NULL OR n.folder_id = filter_folder_id)
    AND (1 - (n.embedding <=> query_embedding)) >= match_threshold
  ORDER BY n.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Grant execute permissions
GRANT EXECUTE ON FUNCTION public.match_notes TO authenticated;
GRANT EXECUTE ON FUNCTION public.match_notes_by_folder TO authenticated;

COMMENT ON FUNCTION public.match_notes IS 
'Semantic search using 384-dim embeddings from Xenova/all-MiniLM-L6-v2';

COMMENT ON FUNCTION public.match_notes_by_folder IS 
'Semantic search filtered by folder using 384-dim embeddings';

-- =====================================================
-- 4. Verification queries
-- =====================================================

-- Check embedding dimension
SELECT atttypmod - 4 AS embedding_dimension
FROM pg_attribute
WHERE attrelid = 'public.notes'::regclass 
  AND attname = 'embedding';

-- Check if canvas_versions table exists and has data
SELECT 
  COUNT(*) as version_count,
  COUNT(DISTINCT canvas_id) as canvases_with_versions
FROM public.canvas_versions;

-- Check RLS policies
SELECT tablename, policyname, cmd 
FROM pg_policies 
WHERE schemaname = 'public' 
  AND tablename IN ('canvas_versions', 'notes')
ORDER BY tablename, policyname;

-- Success message
DO $$
BEGIN
  RAISE NOTICE '✓ Migration completed successfully!';
  RAISE NOTICE '  - Embedding dimension set to 384';
  RAISE NOTICE '  - canvas_versions table created';
  RAISE NOTICE '  - Semantic search functions updated';
  RAISE NOTICE '';
  RAISE NOTICE 'NEXT STEPS:';
  RAISE NOTICE '1. Run embedding backfill: POST /api/admin/backfill-embeddings';
  RAISE NOTICE '2. Test semantic search in the UI';
  RAISE NOTICE '3. Verify canvas version history works';
END $$;
